### ISSUE TITLE
gammazero/deque now uses generics

### ISSUE THREAD

**Issue by 2785** [alexander-yu/stream#2]
Wonder if you would take a PR to upgrade deque to later versions that use generics. Would almost certainly cause a breaking change to this package for it'll require a minimum go version. Totally understand if there's no appetite.

**Comment by alexander-yu** [comment]
I'd be happy to take such a PR! So long as the new package version is tagged with new semantic version (I'd actually never added versioning to this package so we'd probably want to do that), and the breaking change is made clear in a changelog file.

**Comment by 2785** [comment]
Yeah I figured there being no existing sem ver may cause a bit of a problem for consumers of the package - as they'd be on the master branch pseudo-version. But then again I guess once someone attempted an upgrade they'll immediately be hit with a "thing doesn't compile", so probably alright. 

I'm happy to PR, re: versioning I think either `v1.0.0` -> `v2.0.0` or `v0.1.0` -> `v0.2.0` would work. Whichever you prefer :)

**Comment by alexander-yu** [comment]
Yeah, makes sense, thanks! Let's go with `v0.2.0` for the time being.
